name: CI

on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Pack main package
        run: pnpm run lint && pnpm run repack
      - name: Install example dependencies
        run: pnpm i
        working-directory: ./example
      - name: Run example's tests
        run: pnpm test
        working-directory: ./example

